import "dotenv/config";
import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join } from "path";

const API_BASE = "https://api.sermonaudio.com/v2/node";
const API_KEY = process.env.SERMONAUDIO_API_KEY!;
const BROADCASTER_ID = process.env.SERMONAUDIO_BROADCASTER_ID!;
const DATA_DIR = join(process.cwd(), "data", "sermons");
const PAGE_SIZE = 100;
const DELAY_MS = 200;

if (!API_KEY || !BROADCASTER_ID) {
  console.error(
    "Missing SERMONAUDIO_API_KEY or SERMONAUDIO_BROADCASTER_ID in .env"
  );
  process.exit(1);
}

mkdirSync(DATA_DIR, { recursive: true });

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function decodeHTMLEntities(text: string): string {
  return text
    .replace(/&#039;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

async function apiFetch(url: string) {
  const res = await fetch(url, {
    headers: { "X-Api-Key": API_KEY },
  });
  if (!res.ok) {
    throw new Error(`API error ${res.status}: ${await res.text()}`);
  }
  return res.json();
}

async function fetchTranscriptText(downloadURL: string): Promise<string> {
  const res = await fetch(downloadURL);
  if (!res.ok) {
    console.warn(`  Failed to download transcript: ${res.status}`);
    return "";
  }
  return res.text();
}

interface APISermon {
  sermonID: string;
  fullTitle: string;
  displayTitle: string;
  bibleText: string | null;
  subtitle: string | null;
  moreInfoText: string | null;
  eventType: string | null;
  keywords: string | null;
  preachDate: string | null;
  speaker: { displayName: string; speakerID: number };
  series: { seriesID: number } | null;
  transcript: {
    downloadURL: string | null;
    language: string | null;
    autoGenerated: boolean;
  } | null;
}

interface APISermonsList {
  results: APISermon[];
  totalCount: number | null;
  next: string | null;
}

async function downloadAllSermons() {
  let page = 1;
  let totalDownloaded = 0;
  let totalSkipped = 0;
  let totalNoTranscript = 0;
  let hasMore = true;

  console.log(`Downloading sermons for broadcaster: ${BROADCASTER_ID}`);

  while (hasMore) {
    const url = `${API_BASE}/sermons?broadcasterID=${BROADCASTER_ID}&pageSize=${PAGE_SIZE}&page=${page}&sortBy=oldest`;
    console.log(`\nFetching page ${page}...`);

    const data: APISermonsList = await apiFetch(url);
    const sermons = data.results;

    if (page === 1 && data.totalCount) {
      console.log(`Total sermons found: ${data.totalCount}`);
    }

    if (sermons.length === 0) {
      hasMore = false;
      break;
    }

    for (const sermon of sermons) {
      const filePath = join(DATA_DIR, `${sermon.sermonID}.json`);

      if (existsSync(filePath)) {
        totalSkipped++;
        continue;
      }

      if (!sermon.transcript?.downloadURL) {
        totalNoTranscript++;
        continue;
      }

      console.log(
        `  Downloading: ${sermon.displayTitle || sermon.fullTitle} (${sermon.sermonID})`
      );

      const transcriptText = await fetchTranscriptText(
        sermon.transcript.downloadURL
      );

      if (!transcriptText) {
        totalNoTranscript++;
        continue;
      }

      const decode = (s: string | null) =>
        s ? decodeHTMLEntities(s) : null;

      const sermonData = {
        sermonID: sermon.sermonID,
        title: decodeHTMLEntities(sermon.fullTitle),
        displayTitle: decodeHTMLEntities(sermon.displayTitle),
        preacher: sermon.speaker?.displayName ?? "Unknown",
        preacherID: sermon.speaker?.speakerID ?? 0,
        preachDate: sermon.preachDate,
        bibleText: decode(sermon.bibleText),
        series: sermon.series ? String(sermon.series.seriesID) : null,
        eventType: decode(sermon.eventType),
        keywords: decode(sermon.keywords),
        subtitle: decode(sermon.subtitle),
        moreInfoText: decode(sermon.moreInfoText),
        transcript: transcriptText,
      };

      writeFileSync(filePath, JSON.stringify(sermonData, null, 2));
      totalDownloaded++;

      await sleep(DELAY_MS);
    }

    hasMore = data.next !== null;
    page++;
    await sleep(DELAY_MS);
  }

  console.log(`\nDone!`);
  console.log(`  Downloaded: ${totalDownloaded}`);
  console.log(`  Skipped (already exists): ${totalSkipped}`);
  console.log(`  No transcript: ${totalNoTranscript}`);
}

downloadAllSermons().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
